### ISSUE TITLE
Fix Hover State Color on Menu Items

### ISSUE THREAD

**Issue by gitdistill** [gitdistill/eeonyx-theme#1]
Currently defaulting to boostrap's blue for non-open menu

**Comment by jasperSpeicher** [comment]
Erik says:

It seems to veer towards a blue, I would opt for a green tint instead, lets try this: #116600. I would also invert the color behavior. They go to black on rollover/select, this new green tint when not selected. When the menu opens the default unselected colors should also be this green, not black. Remove the state where it goes grey if it is not selected; it resembles a disabled state too much, there isn’t really a need for it if we make the selected state obvious enough, it does not pass color contrast accessibility, and it could confuse a disabled state elsewhere in the site. 
![image](https://cloud.githubusercontent.com/assets/930901/17259762/d990cf5c-5581-11e6-8834-8f697bbfa681.png)
